# Generated by Django 5.0.6 on 2024-07-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
