# Generated by Django 5.0.6 on 2024-07-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0001_initial'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_category',
            name='task_model',
            field=models.ManyToManyField(related_name='categories', to='TaskModel.taskmodel'),
        ),
    ]
