# Generated by Django 5.0.6 on 2024-07-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0002_alter_task_category_task_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_category',
            name='task_model',
        ),
    ]
