# Generated by Django 5.0.6 on 2024-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskCategory', '0003_remove_task_category_task_model'),
        ('TaskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_category',
            field=models.ManyToManyField(to='TaskCategory.task_category'),
        ),
    ]
