# Generated by Django 5.0.6 on 2024-07-05 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0002_taskmodel_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Task_Assign_Date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
