# Generated by Django 5.0.6 on 2024-07-05 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskModel', '0003_alter_taskmodel_task_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Task_Assign_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
