# Generated by Django 5.0.6 on 2024-07-13 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_model/media/uploads/')),
                ('car_name', models.CharField(max_length=50)),
                ('car_description', models.TextField()),
                ('car_price', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand_model.brand')),
            ],
        ),
    ]
