# Generated by Django 5.0.6 on 2024-07-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0003_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
